FROM node:12-alpine

LABEL maintainer="Puppers Team"

# XXX: Ideally we wouldn't need to install git here, but it seems Git is needed for the typescript node module. Maybe in the future we'll be able to remove the need for the git dependency.
RUN apk add bash git

WORKDIR /app

COPY package*.json /app/
RUN npm --prefer-offline --no-audit --progress=false --no-optional ci

VOLUME /app/node_modules
