apiVersion: v1
kind: ServiceAccount
metadata:
  name: pt-gitlab-admin
  # XXX: This might need to be changed for ci deploys
  namespace: pt-gitlab
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pt-gitlab-admin
  # XXX: This might need to be changed for ci deploys
  namespace: pt-gitlab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pt-gitlab-admin
  # XXX: This might need to be changed for ci deploys
  namespace: pt-gitlab
